### ISSUE TITLE
Execution halted in loop with echoGetEffluent() due to curl_fetch_memory() error

### ISSUE THREAD

**Issue by rburghol** [mps9506/echor#49]
Long batch processing jobs can fail when connection is reset by peer.  Error occurs in curl_fetch_memory call -- this may be a curl issue, or this may be handleable in this module, unsure which is the approach.  I am going to look into the code herein to see if another approach exists that can handle resets gracefully.

```
Error in curl::curl_fetch_memory(url, handle = handle) :
  SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Calls: echoGetEffluent ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
```

**Comment by rburghol** [comment]
I  think the error may be here in downloadEffluentChart(), and can be mitigated by using the httr function RETRY(verb, url = NULL, config = list()). Looking for feedback on my proposed solution.

From this:
```
downloadEffluentChart <- function(p_id, verbose, queryDots) {
...
  ## Make the request
  request <- httr::GET(getURL, httr::accept("text/csv"))
```

To this: I can get a successful data retrieval using RETRY()
```
getURL <- "https://ofmpub.epa.gov/echo/eff_rest_services.download_effluent_chart?p_id=VA0005291&parameter_code=50050&start_date=01/01/2019&end_date=12/31/2019"

httr::RETRY("GET", getURL, httr::accept("text/csv"))
```

**Comment by mps9506** [comment]
Thanks! That does seem like a more robust way to do it. I think other API packages use `RETRY` also (this is my first attempt at an API package and was a lot more than I anticipated). It might take me a few days to get the change integrated into the package. I probably need to update elsewhere in the package also.

**Comment by mps9506** [comment]
@rburghol I've updated to `RETRY` on the development branch and it looks like it is working. One unit test seems to fail parsing the downloaded csv's but when I use the function outside of the test environment it works fine.
I want to do some more troubleshooting to figure out why the test fails and maybe put in more informative failure messages before I release a new version. In the meantime, if you would like to try the development branch:
```r
remotes::install_github("mps9506/echor", ref = "dev0.1.5")
```

If you run into any issue let me know! Thanks.

**Comment by rburghol** [comment]
Thanks! Will do and report back if anything goes awry.

**Comment by mps9506** [comment]
@rburghol just fyi, v0.1.5 has been pushed to CRAN and the various build should be available over the next day or so. Thanks a bunch for the feedback!
