### ISSUE TITLE
get_download does not support queries returning more than 100k records

### ISSUE THREAD

**Issue by benamie** [mps9506/echor#79]
I'm having trouble running queries that return more than 100k results. For example, when I run the following:

```
facilities <-
  echoWaterGetFacilityInfo(output = 'df',
                           qcolumns = "1",
                           p_st = "GA")
```

I get a dataframe that looks like this:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/17105526/221391801-d564e8d4-c1d1-470f-b727-6ea0287f8fc0.png">

Is this expected behavior?

What seems like is happening is that the original query has a result set of around 122k records, and the `get_download` endpoint returns an error when requesting a result of more than 100k records. Trying this query directly via the ECHO Swagger:

```
https://echodata.epa.gov/echo/cwa_rest_services.get_download?output=CSV&qid=MY_QUERY_ID&qcolumns=1
```

 I get the following:

```
<b>FILE OUTPUT FAILED</b>
<br />
<b>ERROR MESSAGE:</b> This query of 122923 exceeds the maximum rows allowed for a download of 100000.  Please modify your selection.
```

I think what should happen in this case is that echor should fall back to using the `get_qid` endpoint, which seems to allow pagination.

**Comment by mps9506** [comment]
@benamie thanks for the report!

**Comment by mps9506** [comment]
This is fixed in the current dev versions on github and (in a few hours) the r-universe build.
It will be a few weeks before I release to CRAN since I submitted 0.1.7 less than two weeks ago. Feel free to reopen this if there are any issues.
